// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXi-R9OBLH2PKelT34gLjJoHsJLalPBO8',
    appId: '1:1022929483544:web:59d3d9af3f43c4409cd06d',
    messagingSenderId: '1022929483544',
    projectId: 'crystal-upvc',
    authDomain: 'crystal-upvc.firebaseapp.com',
    storageBucket: 'crystal-upvc.firebasestorage.app',
    measurementId: 'G-Q0DVQE78ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcUUjaco-MKt-lhTG8aj8qBOL3D0CHeLM',
    appId: '1:1022929483544:android:a551b9febb02a0799cd06d',
    messagingSenderId: '1022929483544',
    projectId: 'crystal-upvc',
    storageBucket: 'crystal-upvc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBX5zIpC_y2TJjCmHWr9icudeem9nryrE',
    appId: '1:1022929483544:ios:2d53a5fa7fb3a7169cd06d',
    messagingSenderId: '1022929483544',
    projectId: 'crystal-upvc',
    storageBucket: 'crystal-upvc.firebasestorage.app',
    iosBundleId: 'com.example.crystalUpvc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBX5zIpC_y2TJjCmHWr9icudeem9nryrE',
    appId: '1:1022929483544:ios:2d53a5fa7fb3a7169cd06d',
    messagingSenderId: '1022929483544',
    projectId: 'crystal-upvc',
    storageBucket: 'crystal-upvc.firebasestorage.app',
    iosBundleId: 'com.example.crystalUpvc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXi-R9OBLH2PKelT34gLjJoHsJLalPBO8',
    appId: '1:1022929483544:web:3ab0198fdd3990039cd06d',
    messagingSenderId: '1022929483544',
    projectId: 'crystal-upvc',
    authDomain: 'crystal-upvc.firebaseapp.com',
    storageBucket: 'crystal-upvc.firebasestorage.app',
    measurementId: 'G-49C2NXG3M8',
  );
}
